site_name: Arista Federal Newsletter

site_url: https://AristaFederal.github.io/NewsLetter/
repo_name: AristaFederal/NewsLetter
docs_dir: docs/
edit_uri: edit/main/docs/

markdown_extensions:
- abbr
- attr_list
- md_in_html
- admonition
- tables
- def_list
- pymdownx.details
- pymdownx.superfences
- pymdownx.snippets
- toc: 
    permalink: true  
- pymdownx.tasklist:  
    custom_checkbox: true

theme:
  name: material
  icon:
    admonition:
      quote: octicons/quote-16
      note: octicons/tag-16
  palette:
    primary: custom
  logo: 
  favicon: img/arista_logo.png

nav:
  - www.aristafederal.com: http://www.aristafederal.com
  - April 2025: index.md
  - March 2025: March2025.md

extra_css:
  - stylesheets/extra.css

copyright: Copyright &copy; 2025 Arista Networks. You are receiving this newsletter as a customer of Arista. To stop receiving newsletters please contact fed@aristafederal.com

